### PR TITLE
WIP: Add a revision_accepter role, which builds the small C# program

### PR DESCRIPTION
**Pull request by jure**
Add a revision_accepter role, which builds the small C# program using Mono. Also adds Vagrant development setup support with `vagrant up` and ansible.

Had some SSH issues with Ansible, due to the default user in playbooks being root, and by default you can't ssh into root on Vagrant boxes. Then some repositories are only present in 14.10, not in the LTS 14.4 (Like postgresql-9.4). Also a bit of back and forth with the .env configuration, i.e. where to place it and so on.

I'm currently provisioning/building a box with `vagrant up` and I'll report back here about how it goes. I think the only remaining thing is to forward port 80 and add a shared /var/www/ihat folder, and that will be that. But I'll wait for this box to build, and if all goes well, remove the WIP prefix in the title.

### CODE REVIEW

**Comment by jure** [comment]
Hmm, still some issues with .env loading, seems like it needs to be loaded within the Ansible context on the guest machine, which is a bit funny. Doesn't Ansible run locally?

```
fatal: [default] => One or more undefined variables: 'DATABASE_NAME' is undefined
```

**Comment by jure** [comment]
This should be good to go finally. I'll run it one last time from scratch and remove the WIP then.

`vagrant up` should give you a dev environment out of the box. I'll add some docs about how to use it.

**Comment by mikem** [comment]
Does it make it any easier to separate the Vagrant bit into another PR?

**Comment by jure** [comment]
It's in the same PR as that's how I was testing my ansible playbooks, but sure I can separate it out. What would be the benefit though? Or are you not sure whether or not the Vagrant bit should be merget at all?

**Comment by mikem** [comment]
I suggested it because from your comments above it seemed to introduce issues. If those are resolved, then no need to split this up.

**Comment by jure** [comment]
Ah, I see! Yes, those (ENV variable issues) were resolved in https://github.com/Tahi-project/ihat/commit/bf19536261ee07e4c114f4d8997c2694d12d79c5

**Comment by mikem** [comment]
Looks alright to me. @surfacedamage can you also sign off, please?

**Comment by surfacedamage** [comment]
:+1:

**Comment by neo-tahi** [comment]
I am waiting to merge this until the circleci integration with ihat is complete.  Currently blocked by rubygems having connectivity issues.

**Pull request merged**
