### PR TITLE
Easy development setup with Vagrant & Docker

### PR DESCRIPTION
**Pull request by jure**

### CODE REVIEW

**Comment by mikem** [comment]
@jure how's this setup working out for you? Are you using it at all? Is it at the stage where it can be merged?

**Comment by jure** [comment]
Right, I started using oxgarage in a Docker container separately, as the asynchronicity of ihat-pipeline was an issue for my testing framework. The only thing missing here is the sharing of volumes/files from host to guest VM to Docker, as I did in https://github.com/Tahi-project/conversion-optimization/blob/master/Vagrantfile#L8, to allow for instant sync during development. I will add that last thing (I expect some permissions issues) and then it will be ready to merge.

Have any other alternatives for easy development turned up?

**Comment by mikem** [comment]
@jure the project can now be [deployed with Ansible](https://github.com/Tahi-project/ihat#server-provisioning) (see the [`ansible` directory](https://github.com/Tahi-project/ihat/tree/master/ansible) in the project root). Maybe that allows you to eliminate Docker from the equation and just launch a VM with Vagrant?

**Comment by jure** [comment]
There is a benefit to using the same tool for local development setup and deployment, and yes, it is possible to simply provision a Vagrant VM with Ansible (and maintain the `vagrant up` ease of setup), for a concrete example: https://danielgroves.net/notebook/2014/05/development-environments/

In my mind it doesn't make a lot of sense to maintain a Docker way just for development, if we're not using it in production. Your call!

**Comment by mikem** [comment]
Alright, so since we don't intend to merge this, I'm closing it.

Whoever ends up getting iHat working with Vagrant and Ansible can open another PR.

**Pull request closed without merging**
